### ISSUE TITLE
Use removeGlobalOnLayoutListener for API 15+

### ISSUE THREAD

**Issue by mattleibow** [team-supercharge/ShimmerLayout#12]
Have you considered using `removeGlobalOnLayoutListener` here:

https://github.com/team-supercharge/ShimmerLayout/blob/master/shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java#L98

This way, you can drop the minimum version of Android required to API 15 (v4.0.3). Although not a major jump, this makes this library available a few more devices.

**Comment by mattleibow** [comment]
If you tweak this:
https://github.com/team-supercharge/ShimmerLayout/blob/master/shimmerlayout/src/main/java/io/supercharge/shimmerlayout/ShimmerLayout.java#L273-L279

You can drop the API to 14+

**Comment by WonderCsabo** [comment]
What is the issue with the getColor method?

**Comment by mattleibow** [comment]
The `return getContext().getColor(id);` does not exist on API 14. It does on 15+.

**Comment by WonderCsabo** [comment]
Actually Context.getColor() was added in API 23 and as you can see, we only call that above for older versions we fallback on code which is compatible with API 1.

**Comment by mattleibow** [comment]
ah, you are right! my mind skipped over the whole if statement :)

**Comment by veghtomi** [comment]
Now the minimum API is 14.
