### ISSUE TITLE
OutOfMemory Exception

### ISSUE THREAD

**Issue by anderscheow** [team-supercharge/ShimmerLayout#25]
![30528146-93a5032c-9c62-11e7-8a8f-97009db6f6b7](https://user-images.githubusercontent.com/11788504/30735359-4acad328-9fb1-11e7-9848-9ddfcedce1b5.png)
Getting this when try to run it

**Comment by veghtomi** [comment]
@anderscheow Could you provide me with the details of your application? How big are the layouts you are animating, how many animations are running at the same time? And what kind of phone you are using as it seems that it fails to allocate around 3 megabytes which is quite unreal with todays phones.

**Comment by anderscheow** [comment]
@veghtomi i do not have much info on this, this problem occurred to one of the phone when the app go live to public, this is the only info i can get

**Comment by veghtomi** [comment]
@anderscheow and what about the layout itself? I guess this animation is applied only a few places in your app. Could you list them so I can figure out why happened?

So far I believe the phone itself has very little free memory and it is not library related issue.

**Comment by anderscheow** [comment]
@veghtomi I did applied that to 2 layouts, they did load when the app is launched. Is there any possible way to handle this?

**Comment by veghtomi** [comment]
@anderscheow The only possible way it can happen is whether those layouts are huge (multiple of the screen height) or the phone this issue happened on is a low-end phone. How many times this issue occured?

**Comment by anderscheow** [comment]
@veghtomi so far only has 1 device got this issue. i also suspect is low-end phone. Btw thanks for the help :)

**Comment by veghtomi** [comment]
@anderscheow You are welcome! :) If you have some issue with the lib, just write me!

**Comment by veghtomi** [comment]
@anderscheow Check out the new 2.0.0 version where memory usage decreased dramatically.
