### ISSUE TITLE
Documentation For Custom Properties

### ISSUE THREAD

**Issue by ShaishavGandhi** [team-supercharge/ShimmerLayout#37]
One suggestion is to have a table of properties that ShimmerLayout exposes and describe what it does, what the allowed inputs are etc in the Readme.md
There aren't many properties and it would be very useful since everyone's configuration will be completely different and it will be useful to have that table to consult. 
I'm happy to take a stab at it.

**Comment by veghtomi** [comment]
Quite an idea! I would be very happy if you do it. The best solution would be I believe if You could create a wiki page for it. After the readme would be also updated with a reference to this wiki page.

**Comment by ShaishavGandhi** [comment]
That sounds good. I'll submit a PR over the weekend.

**Comment by veghtomi** [comment]
Wiki is created!
