### ISSUE TITLE
problem when implement into recyclerview  

### ISSUE THREAD

**Issue by leyvien** [team-supercharge/ShimmerLayout#38]
i upload sort clip to demonstration this problem
https://media.giphy.com/media/xT1Ra4ix78tdhSqnmw/giphy.gif

i have recyclerview with 20 items, the problem happen when i scroll down and then scroll up
(Sorry about my English)

**Comment by veghtomi** [comment]
@leyvien It is because of the RecyclerView default behaviour. When you scrolll down or up, the viewholders will be binded again, which means new startAnimation will be called. That is the reason why the shimmerAnimations do not start together.

I suggest using the `setLayoutFrozen(boolean frozen)` method of the `RecyclerView` which will disable scrolling for the time of the loading.

**Comment by leyvien** [comment]
@veghtomi Thank you for quick response.
Is there any other way to achieve that without using  setLayoutFrozen, i still need scrolling 
(i already try Facebook shimmer library but it make my app very slow, that why i choose your library )

**Comment by veghtomi** [comment]
And the Facebook library worked as expected? I will think about it. Maybe if there is a way to disable recycling viewholders it could work.

**Comment by leyvien** [comment]
@veghtomi Yes, Facebook library worked as expected!

**Comment by veghtomi** [comment]
Thanks! I will check it!

**Comment by veghtomi** [comment]
@leyvien could you provide me code when the Facebook shimmer library worked as expected? I tried it, however I experienced the same issues.

**Comment by leyvien** [comment]
@veghtomi Oh sorry, my mistake!
After checked, Facebook also have same issue

**Comment by mgrzechocinski** [comment]
Hi, @veghtomi, on the attached GIF, why 7th+ rows are not being animated? I'm facing similar issue right now when trying to use ShimmerLayout in a view which is recycled using ViewHolder. Sometimes thoses views are not being animated at all. In my case, it's always the first view which is recycled. 

In my Adapter's `onBindViewHolder` I try to stop the animation and start it again for the recycled view, but without success.

 Any ideas why the animation doesn't start?

**Comment by mgrzechocinski** [comment]
After further investigation - it looks like the problem with `ViewTreeObserver.OnGlobalLayoutListener` in `startShimmerAnimation` which doesn't get called for recycled views, therefore animation is never being launched for them.

**Comment by veghtomi** [comment]
Hi @mgrzechocinski, the solution for this issue is using `ViewTreeObserver.OnPreDrawListener` instead of `ViewTreeObserver.OnGlobalLayoutListener`. I fixed it, just not created a pull request. I will release it at the next week. Until that try this solution.

**Comment by mgrzechocinski** [comment]
Hi, @veghtomi, so you mean something like this? #39 

I tried it but unfortunately I'm still able to reproduce recycled views without animation, especially when doing fasts scroll on long list.

**Comment by mgrzechocinski** [comment]
Ok, I looked at the ShimmerLayout.java closely and found that my issue is caused by:

```
@Override
protected void onDetachedFromWindow() {
    resetShimmering();
    super.onDetachedFromWindow();
}
```

It's extremely simple to reproduce. Just have your view holders created, swipe your list down, until at least one view becomes recycled, then swipe up. Your first view, which came back has no animation.

Here's how it looks in logs:

```
D/SHIMER: Animation STOP for position: 0
D/SHIMER: Animation START for position: 0
D/SHIMER: Animation STARTING for position: 0 with 84530817
D/SHIMER: Animation STOP for position: 1
D/SHIMER: Animation START for position: 1
D/SHIMER: Animation STARTING for position: 1 with 223466278
D/SHIMER: Animation STOP for position: 2
D/SHIMER: Animation START for position: 2
D/SHIMER: Animation STARTING for position: 2 with 261139303
D/SHIMER: Animation STOP for position: 3
D/SHIMER: Animation START for position: 3
D/SHIMER: Animation STARTING for position: 3 with 226266388

==== SWIPE DOWN =====
D/SHIMER: Animation STOP for position: 4
D/SHIMER: Animation START for position: 4
D/SHIMER: Animation STARTING for position: 4 with 26858681
D/SHIMER: Animation RESETING for position: -1 with 84530817 //caused by onDetachedFromWindow
D/SHIMER: Animation STOPPING for position: 0 with 84530817

=== SWIPE UP =====
D/SHIMER: Animation RESETING for position: -1 with 26858681 //caused by onDetachedFromWindow
D/SHIMER: Animation STOPPING for position: 4 with 26858681
```

I guess `resetShimmering()` in `onDetachedFromWindow()` is generally a good idea, however in the RecyclerView use case it's rather excessive since I do start/stop manually in my `onBindViewHolder`. I do not have a straightforward fix for that, other than removing this line, though. 

I'd appreciate any hints around that.

**Comment by mgrzechocinski** [comment]
Hey, @veghtomi, any updates on this?

**Comment by veghtomi** [comment]
Hi @mgrzechocinski, check the pull request. The CI has failed at your commit.

**Comment by veghtomi** [comment]
The solution for this is waiting to be reviewed. Until then you can test it. To work perfectly at RecyclerView, I suggest that starting the animation should be placed inside `void onViewAttachedToWindow (VH holder)` at the Adapter class.

**Comment by veghtomi** [comment]
The new 1.2.0 version solves this issue!
