### ISSUE TITLE
Right to Left Animation

### ISSUE THREAD

**Issue by frozenex** [team-supercharge/ShimmerLayout#48]
Is it possible to reverse the animation say from right to left instead of left to right ??

**Comment by veghtomi** [comment]
@frozenex no, it is not possible now, but I will implement it and the next week it will be released so you can use it!

**Comment by frozenex** [comment]
@veghtomi Thank you, looking forward to the update.

**Comment by veghtomi** [comment]
@frozenex feature is done. After doing the testing, it will be released around Thursday or Friday, but I will write here.

**Comment by veghtomi** [comment]
@frozenex reverse animation is ready to be used at the new version of the library, in **2.1.0**

Also, you can now add negative angle to the shimmer line.

**Comment by frozenex** [comment]
@veghtomi Thanks for implementing the feature... Just now implemented it in the app, working as expected!

**Comment by veghtomi** [comment]
You are welcome! :)
