### ISSUE TITLE
Memory leak - ValueAnimator holding a reference to the view

### ISSUE THREAD

**Issue by dorsamet** [team-supercharge/ShimmerLayout#54]
Hi,

I received this memory leak:

![whatsapp image 2018-04-04 at 3 21 33 pm](https://user-images.githubusercontent.com/11819137/38314187-56bcda4e-382e-11e8-8205-f3fef4e6ca2b.jpeg)

![whatsapp image 2018-04-04 at 3 21 33 pm](https://user-images.githubusercontent.com/11819137/38314147-456886c6-382e-11e8-964e-6c8d94b9e56c.jpeg)

I've seen a similar issue being posted on the Facebook Github.
We currently extend the layout to play around with the animation (delay start, have it play for a bit, and then stop it). While this manipulation of the animation does require a reference to the view, I am having a hard time understanding why, since the view doesn't reference the handler holding a reference to a message, and so on.
WDYT?

**Comment by veghtomi** [comment]
@dorsamet If you could show/send me code I could check it. Basically, the lib should not leak memory as when it is detached, all the bitmaps are recycled, animation is cancelled and listeners also removed.

**Comment by veghtomi** [comment]
Since no other information about the leak has arrived, I am closing this issue.
