### ISSUE TITLE
Shimmering Stop in RecyclerView

### ISSUE THREAD

**Issue by ArcherEmiya05** [team-supercharge/ShimmerLayout#55]
Whenever I scroll in Recyclerview the shimmering part is stop just like in this video.

https://drive.google.com/file/d/1jr32P_av4cP9tHqW-UBkOnrSoWDqO5LI/view

**Comment by GuanacoDevs** [comment]
I solved it using the second to last comment of #38 
```
    @Override
    public void onViewAttachedToWindow(@NonNull StoreViewHolder holder) {
        holder.startAnimation();
        super.onViewAttachedToWindow(holder);
    }
```

**Comment by veghtomi** [comment]
@ArcherEmiya05 it is not an issue, it can be fixed as @GuanacoDevs wrote in the previous comment.

 The reason behind this, that when the particular list item/Viewholder is scrolled off the screen, the View gets detached which stops the animation. The `RecyclerView` caches that ViewHolder and the next time the `onBindViewHolder()` method will not be called as the data in the Viewholder has not changed. 

 The `onViewAttachedToWindow()` method will be called every time, even if the ViewHolder was in the cache so the start animation method have to be called from there.

**Comment by ArcherEmiya05** [comment]
Wow, thanks I will try it!
