### ISSUE TITLE
Comparison with Facebook shimmer library 0.2.0 is not available

### ISSUE THREAD

**Issue by usmanrana07** [team-supercharge/ShimmerLayout#60]
Can you update the graph comparison against Facebook shimmer library 0.2.0 ? Is ShimmerLayout still better than that?

**Comment by veghtomi** [comment]
@usmanrana07 Thanks for the remark, I will do the comparison soon.

**Comment by veghtomi** [comment]
@usmanrana07 I did the comparison with Facebook Shimmer 0.3.0 and the results were almost equal, so I removed the performance part. On almost equal I mean that in one situation my library consumed less by half MB, on the other situation the Facebook one.
