### ISSUE TITLE
Getting dark shimmer animation for big views

### ISSUE THREAD

**Issue by chathura2020** [team-supercharge/ShimmerLayout#63]
I have even tested this on the sample app as well. It shows the dark animation like in the gif. How to fix this issue? 
![shimmer](https://user-images.githubusercontent.com/3771098/43363082-dec2d1d2-9319-11e8-9e20-28f530043716.gif)

**Comment by chathura2020** [comment]
it worked after I adjust color of views and shimmer color

**Comment by veghtomi** [comment]
@chathura2020 yes, to achieve the final effect, you have to modify both the shimmer color and the background of the views.
