### ISSUE TITLE
Issue with invisible RecyclerView item

### ISSUE THREAD

**Issue by ankudryavtsev** [team-supercharge/ShimmerLayout#68]
Hi!

**Case**:
We subscribe to some event and start/stop shimmer animation in onSubscribe/onFinally in bindView() of ViewHolders of our RecyclerView.
In ViewHolders which are visible to a user there is no problem but in elements which are off the screen shimmer animation starts but doesn't stop although stopShimmerAnimation() called.
If you scroll up and down bindView() will be called again and shimmer animation will be stopped.

**Comment by veghtomi** [comment]
Hi @kudrandrew, 

Could you attach a sample code?

**Comment by ankudryavtsev** [comment]
Hi @veghtomi,
I tried to create a sample app, but the issue wasn't reproduced.
So we have an issue with our adapter.
Thank you!

**Comment by veghtomi** [comment]
You are welcome!
