### ISSUE TITLE
Improve usage documentation

### ISSUE THREAD

**Issue by omatrot** [team-supercharge/ShimmerLayout#71]
If I've understood ShimmerLayout correctly, it is only about the animation of an existing layout where backgrounds and text colors of existing elements are already set to something like what we have in the sample.

In the real life, at some point I have to show real data.

I initially thought that given an existing layout, and provided with some kind of async task, colors and backgrouds would have been switched to show that loading is in progress and reverted back to initial colors in the layout.

That would have been a real added value.

**Comment by veghtomi** [comment]
Hi @omatrot, yes, it is true that the sample app does not have this feature. However, I believe that the usage of this library (with the provided [Wiki documentation](https://github.com/team-supercharge/ShimmerLayout/wiki)) is very simple so everybody can use it in a way he/she wants.
