### ISSUE TITLE
AAPT: error: duplicate value for resource 'attr/layout_gravity' with config.

### ISSUE THREAD

**Issue by RohitK1992** [team-supercharge/ShimmerLayout#76]
I updated my android studio from 3.1.3 to 3.4 and changed the targetSdkVersion to 28.
PS: classpath 'com.android.tools.build:gradle:3.4.0'. After which I am getting the following compile time error and I am not able to generate the build for my app.

And this is the error displayed:

C:\Users\admin\.gradle\caches\transforms-2\files-2.1\a31c077a0c9e7184e12caa4ae20cff19\res\values\values.xml:4:5-501: AAPT: error: duplicate value for resource 'attr/layout_gravity' with config ''.
    
C:\Users\admin\.gradle\caches\transforms-2\files-2.1\a31c077a0c9e7184e12caa4ae20cff19\res\values\values.xml:4:5-501: AAPT: error: resource previously defined here.
[valuesxml.txt](https://github.com/team-supercharge/ShimmerLayout/files/3158039/valuesxml.txt)

**Comment by RohitK1992** [comment]
Is anybody looking into this ?

**Comment by veghtomi** [comment]
@RohitK1992 I will.

**Comment by RohitK1992** [comment]
@veghtomi Any update ?

**Comment by veghtomi** [comment]
@RohitK1992 
I am using Android Studio 3.4.1 with the same targetSdkVersion and gradle version.
Also, the library does not define a property called _layout_gravity_. See your attached file.

Maybe try to use Invalidate Caches / Restart and play with the libraries/versions you use for the project.
