### ISSUE TITLE
Auto start

### ISSUE THREAD

**Issue by talenguyen** [team-supercharge/ShimmerLayout#9]
My opinion is it's better if we have option to auto start animation when it's ready than only java option.

**Comment by veghtomi** [comment]
In the next release (at the weekend) I will add an autoStart attribute to it.

**Comment by k0shk0sh** [comment]
@veghtomi I hope you don't mind, but i'm planning to take the issues that are currently opened including this, as i'm planning to use the library in https://github.com/k0shk0sh/FastHub and love to contribute to it :) . will be submitting a PR in awhile.

**Comment by veghtomi** [comment]
Any contribution is appreciated @k0shk0sh ! Just ignore the #12 issue now.

**Comment by k0shk0sh** [comment]
@veghtomi  Already did before I see your response, would you consider or stash my changes?

**Comment by veghtomi** [comment]
@k0shk0sh Feel free to submit! :)

**Comment by k0shk0sh** [comment]
@veghtomi  cool, I'll be committing the PR right away.

**Comment by veghtomi** [comment]
Feature is added.
